name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.9, 3.8, 3.7]
    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
    - name: Set up Python
      uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e # v2.3.4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pip dependencies
      run: pip install -r requirements-test.txt
    - name: Run tests
      run: pytest tests/ -v

    - name: type check
      run: mypy .
